version: '3.7'

services:
  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER:
      MINIO_ROOT_PASSWORD:
      MINIO_PROMETHEUS_AUTH_TYPE: public
      MINIO_PROMETHEUS_URL: http://prometheus:9090
    command: server --console-address ":9001" /data
    networks:
      minecraft-net:
    hostname: minio
    ports:
      # - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://minio:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - data:/data
    restart:
      always
  
  minio-init:
    image: minio/mc
    depends_on:
      - minio   
    environment:
      MINIO_ROOT_USER:
      MINIO_ROOT_PASSWORD:
      RESTIC_USER:
      RESTIC_PASSWORD:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
    networks:
      minecraft-net:
    entrypoint: ./scripts/minio-init.sh
    volumes:
      - ./scripts:/scripts:ro

  prometheus:
    image: prom/prometheus
    command: --config.file=/etc/prometheus/prometheus.yml
    networks:
      minecraft-net:
    volumes:
        - ./prometheus.yml:/etc/prometheus/prometheus.yml

networks:
  minecraft-net:
    name: minecraft-net

volumes:
  data: