global:
    scrape_interval: 10s
    evaluation_interval: 10s
  
scrape_configs:
  - job_name: minio-job-bucket
    metrics_path: /minio/v2/metrics/bucket
    scheme: http
    static_configs:
    - targets: ['minio:9000']
  - job_name: minio-job
    metrics_path: /minio/v2/metrics/cluster
    scheme: http
    static_configs:
    - targets: ['minio:9000']